// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13c-tdMPkXkFumtZNMmHVAbcdIT5n8Pg',
    appId: '1:937906202395:web:7b198270aead8b48e255be',
    messagingSenderId: '937906202395',
    projectId: 'danodalds',
    authDomain: 'danodalds.firebaseapp.com',
    storageBucket: 'danodalds.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1srsnxoUmY-l79CfBvT-DLIZNajOosko',
    appId: '1:937906202395:android:81473d41d95cea64e255be',
    messagingSenderId: '937906202395',
    projectId: 'danodalds',
    storageBucket: 'danodalds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc0RYd4auLwzKi_0QIfGINr9PjXXbbOE0',
    appId: '1:937906202395:ios:7af2a2588ee4b345e255be',
    messagingSenderId: '937906202395',
    projectId: 'danodalds',
    storageBucket: 'danodalds.appspot.com',
    iosBundleId: 'com.example.royalPlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc0RYd4auLwzKi_0QIfGINr9PjXXbbOE0',
    appId: '1:937906202395:ios:7af2a2588ee4b345e255be',
    messagingSenderId: '937906202395',
    projectId: 'danodalds',
    storageBucket: 'danodalds.appspot.com',
    iosBundleId: 'com.example.royalPlate',
  );
}
